### ISSUE TITLE
API keys.

### ISSUE THREAD

**Issue by MallikaKakade** [cnaccio/ApexMerchant#1]
- I want to know what is login and password here and How can I get it from stripe?
I do have stripe account but want to know, login and password represent which API key?

- I used code snippet given by ApexMerchant.
But getting below error:
**ERROR: Sending credit card numbers directly to the Stripe API is generally unsafe. We suggest you use test tokens that map to the test card you are using, see https://stripe.com/docs/testing.**

**Comment by mhamzas** [comment]
@MallikaKakade 
Login and Pass are Api Key and Secret.

**Comment by cnaccio** [comment]
Exactly; you'll get this information from your merchant provider i.e. Slack, Authorize.net, etc..
